# Project-wide Gradle settings.
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djava.net.preferIPv4Stack=true -Dhttp.keepAlive=false
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
